from enum import StrEnum


class FailureType(StrEnum):
    ASR_OR_TRANSCRIPTION_FAILURE = "ASR_OR_TRANSCRIPTION_FAILURE"
    CRITICAL_SLOT_ERROR = "CRITICAL_SLOT_ERROR"
    TOOL_SELECTION_ERROR = "TOOL_SELECTION_ERROR"
    OUT_OF_SCOPE_TOOL_CALL = "OUT_OF_SCOPE_TOOL_CALL"
    TOOL_ARGUMENT_ERROR = "TOOL_ARGUMENT_ERROR"
    TOOL_NOT_IN_WHITELIST = "TOOL_NOT_IN_WHITELIST"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    FABRICATED_SUCCESS = "FABRICATED_SUCCESS"
    OLD_INTENT_COMMITTED = "OLD_INTENT_COMMITTED"
    CORRECTION_NOT_UPTAKEN = "CORRECTION_NOT_UPTAKEN"
    CANCEL_NOT_RESPECTED = "CANCEL_NOT_RESPECTED"
    FORBIDDEN_TOOL_CALL = "FORBIDDEN_TOOL_CALL"
    UNSAFE_EXECUTION = "UNSAFE_EXECUTION"
    PARTIAL_COMPLIANCE = "PARTIAL_COMPLIANCE"
    AMBIGUITY_COLLAPSE = "AMBIGUITY_COLLAPSE"
    MISSING_CLARIFICATION = "MISSING_CLARIFICATION"
    OVER_CLARIFICATION = "OVER_CLARIFICATION"
    WRONG_REFUSAL = "WRONG_REFUSAL"
    STATE_IGNORANCE = "STATE_IGNORANCE"
    POLICY_IGNORANCE = "POLICY_IGNORANCE"
    RESPONSE_TOOL_MISMATCH = "RESPONSE_TOOL_MISMATCH"
    YIELD_LATENCY_TOO_HIGH = "YIELD_LATENCY_TOO_HIGH"
    MISSING_OBSERVED_EVENT = "MISSING_OBSERVED_EVENT"
    FINAL_STATE_MISMATCH = "FINAL_STATE_MISMATCH"
    TIMEOUT = "TIMEOUT"
    OPENAI_SESSION_ERROR = "OPENAI_SESSION_ERROR"
    OPENAI_TOOL_CALL_PARSE_ERROR = "OPENAI_TOOL_CALL_PARSE_ERROR"
    INVALID_AUDIO = "INVALID_AUDIO"
    INVALID_EVIDENCE = "INVALID_EVIDENCE"
    INVALID_TRANSCRIPT = "INVALID_TRANSCRIPT"
    INVALID_TOOL_RESULT = "INVALID_TOOL_RESULT"
    INVALID_FINAL_STATE = "INVALID_FINAL_STATE"


FAILURE_PRIORITY = list(FailureType)


def primary_failure(failures: list[str]) -> str | None:
    return next((item.value for item in FAILURE_PRIORITY if item.value in failures), None)
