from enum import StrEnum


class FailureType(StrEnum):
    ASR_OR_TRANSCRIPTION_FAILURE = "ASR_OR_TRANSCRIPTION_FAILURE"
    CRITICAL_SLOT_ERROR = "CRITICAL_SLOT_ERROR"
    TOOL_SELECTION_ERROR = "TOOL_SELECTION_ERROR"
    OUT_OF_SCOPE_TOOL_CALL = "OUT_OF_SCOPE_TOOL_CALL"
    TOOL_ARGUMENT_ERROR = "TOOL_ARGUMENT_ERROR"
    TOOL_NOT_IN_WHITELIST = "TOOL_NOT_IN_WHITELIST"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    FABRICATED_SUCCESS = "FABRICATED_SUCCESS"
    OLD_INTENT_COMMITTED = "OLD_INTENT_COMMITTED"
    CORRECTION_NOT_UPTAKEN = "CORRECTION_NOT_UPTAKEN"
    CANCEL_NOT_RESPECTED = "CANCEL_NOT_RESPECTED"
    FORBIDDEN_TOOL_CALL = "FORBIDDEN_TOOL_CALL"
    YIELD_LATENCY_TOO_HIGH = "YIELD_LATENCY_TOO_HIGH"
    MISSING_OBSERVED_EVENT = "MISSING_OBSERVED_EVENT"
    FINAL_STATE_MISMATCH = "FINAL_STATE_MISMATCH"
    TIMEOUT = "TIMEOUT"
    OPENAI_SESSION_ERROR = "OPENAI_SESSION_ERROR"
    OPENAI_TOOL_CALL_PARSE_ERROR = "OPENAI_TOOL_CALL_PARSE_ERROR"


FAILURE_PRIORITY = list(FailureType)


def primary_failure(failures: list[str]) -> str | None:
    return next((item.value for item in FAILURE_PRIORITY if item.value in failures), None)
